/**
 * Code128B barcode decoder — reads barcode data directly from canvas pixels.
 * Designed to decode barcodes generated by our own barcode-generator.ts.
 * Uses the same PATTERNS table for reliable round-trip encoding/decoding.
 */

const CODE128B_START = 104;
const CODE128_STOP = 106;

const PATTERNS: number[][] = [
  [2,1,2,2,2,2],[2,2,2,1,2,2],[2,2,2,2,2,1],[1,2,1,2,2,3],[1,2,1,3,2,2],
  [1,3,1,2,2,2],[1,2,2,2,1,3],[1,2,2,3,1,2],[1,3,2,2,1,2],[2,2,1,2,1,3],
  [2,2,1,3,1,2],[2,3,1,2,1,2],[1,1,2,2,3,2],[1,2,2,1,3,2],[1,2,2,2,3,1],
  [1,1,3,2,2,2],[1,2,3,1,2,2],[1,2,3,2,2,1],[2,2,3,2,1,1],[2,2,1,1,3,2],
  [2,2,1,2,3,1],[2,1,3,2,1,2],[2,2,3,1,1,2],[3,1,2,1,3,1],[3,1,1,2,2,2],
  [3,2,1,1,2,2],[3,2,1,2,2,1],[3,1,2,2,1,2],[3,2,2,1,1,2],[3,2,2,2,1,1],
  [2,1,2,1,2,3],[2,1,2,3,2,1],[2,3,2,1,2,1],[1,1,1,3,2,3],[1,3,1,1,2,3],
  [1,3,1,3,2,1],[1,1,2,3,1,3],[1,3,2,1,1,3],[1,3,2,3,1,1],[2,1,1,3,1,3],
  [2,3,1,1,1,3],[2,3,1,3,1,1],[1,1,2,1,3,3],[1,1,2,3,3,1],[1,3,2,1,3,1],
  [1,1,3,1,2,3],[1,1,3,3,2,1],[1,3,3,1,2,1],[3,1,3,1,2,1],[2,1,1,3,3,1],
  [2,3,1,1,3,1],[2,1,3,1,1,3],[2,1,3,3,1,1],[2,1,3,1,3,1],[3,1,1,1,2,3],
  [3,1,1,3,2,1],[3,3,1,1,2,1],[3,1,2,1,1,3],[3,1,2,3,1,1],[3,3,2,1,1,1],
  [3,1,4,1,1,1],[2,2,1,4,1,1],[4,3,1,1,1,1],[1,1,1,2,2,4],[1,1,1,4,2,2],
  [1,2,1,1,2,4],[1,2,1,4,2,1],[1,4,1,1,2,2],[1,4,1,2,2,1],[1,1,2,2,1,4],
  [1,1,2,4,1,2],[1,2,2,1,1,4],[1,2,2,4,1,1],[1,4,2,1,1,2],[1,4,2,2,1,1],
  [2,4,1,2,1,1],[2,2,1,1,1,4],[4,1,3,1,1,1],[2,4,1,1,1,2],[1,3,4,1,1,1],
  [1,1,1,2,4,2],[1,2,1,1,4,2],[1,2,1,2,4,1],[1,1,4,2,1,2],[1,2,4,1,1,2],
  [1,2,4,2,1,1],[4,1,1,2,1,2],[4,2,1,1,1,2],[4,2,1,2,1,1],[2,1,2,1,4,1],
  [2,1,4,1,2,1],[4,1,2,1,2,1],[1,1,1,1,4,3],[1,1,1,3,4,1],[1,3,1,1,4,1],
  [1,1,4,1,1,3],[1,1,4,3,1,1],[4,1,1,1,1,3],[4,1,1,3,1,1],[1,1,3,1,4,1],
  [1,1,4,1,3,1],[3,1,1,1,4,1],[4,1,1,1,3,1],[2,1,1,4,1,2],[2,1,1,2,1,4],
  [2,1,1,2,3,2],
];
const STOP_PATTERN = [2, 3, 3, 1, 1, 1, 2];

/**
 * Extract a horizontal scanline of black/white run-lengths from a canvas.
 * Returns array of { isBlack, width } runs.
 */
function getScanlineRuns(
  ctx: CanvasRenderingContext2D,
  y: number,
  width: number,
  threshold = 128,
): { isBlack: boolean; width: number }[] {
  const row = ctx.getImageData(0, y, width, 1).data;
  const runs: { isBlack: boolean; width: number }[] = [];
  let prevBlack = row[0] * 0.299 + row[1] * 0.587 + row[2] * 0.114 < threshold;
  let runWidth = 1;

  for (let x = 1; x < width; x++) {
    const idx = x * 4;
    const gray = row[idx] * 0.299 + row[idx + 1] * 0.587 + row[idx + 2] * 0.114;
    const isBlack = gray < threshold;
    if (isBlack === prevBlack) {
      runWidth++;
    } else {
      runs.push({ isBlack: prevBlack, width: runWidth });
      prevBlack = isBlack;
      runWidth = 1;
    }
  }
  runs.push({ isBlack: prevBlack, width: runWidth });
  return runs;
}

/**
 * Try to match a sequence of 6 run widths (normalized) against known Code128 patterns.
 * Returns the pattern index or -1.
 */
function matchPattern(widths: number[]): number {
  if (widths.length !== 6) return -1;
  const total = widths.reduce((s, w) => s + w, 0);
  // Each Code128 symbol has 11 modules total
  const moduleWidth = total / 11;
  const normalized = widths.map((w) => Math.round(w / moduleWidth));

  for (let i = 0; i < PATTERNS.length; i++) {
    const p = PATTERNS[i];
    let match = true;
    for (let j = 0; j < 6; j++) {
      if (normalized[j] !== p[j]) { match = false; break; }
    }
    if (match) return i;
  }
  return -1;
}

function matchStopPattern(widths: number[]): boolean {
  if (widths.length !== 7) return false;
  const total = widths.reduce((s, w) => s + w, 0);
  const moduleWidth = total / 13; // stop pattern has 13 modules
  const normalized = widths.map((w) => Math.round(w / moduleWidth));
  for (let j = 0; j < 7; j++) {
    if (normalized[j] !== STOP_PATTERN[j]) return false;
  }
  return true;
}

/**
 * Decode a Code128B barcode from a canvas scanline.
 * Returns the decoded text or null.
 */
function decodeScanline(
  ctx: CanvasRenderingContext2D,
  y: number,
  width: number,
  threshold = 128,
): string | null {
  const runs = getScanlineRuns(ctx, y, width, threshold);

  // Find the first black run (start of barcode, after quiet zone)
  let startIdx = 0;
  while (startIdx < runs.length && !runs[startIdx].isBlack) startIdx++;
  if (startIdx >= runs.length - 12) return null; // not enough runs

  // Extract alternating bar/space widths starting from the first black bar
  const barWidths: number[] = [];
  for (let i = startIdx; i < runs.length; i++) {
    barWidths.push(runs[i].width);
  }

  // Try to decode symbols: each symbol is 6 elements (3 bars + 3 spaces)
  // Start code is first 6 elements
  const values: number[] = [];
  let pos = 0;

  // Decode start symbol
  const startWidths = barWidths.slice(pos, pos + 6);
  const startVal = matchPattern(startWidths);
  if (startVal !== CODE128B_START) return null;
  values.push(startVal);
  pos += 6;

  // Decode data symbols until we hit the stop pattern
  const maxSymbols = 50; // safety limit
  for (let s = 0; s < maxSymbols; s++) {
    if (pos + 7 <= barWidths.length) {
      // Check if this is the stop pattern (7 elements)
      const stopWidths = barWidths.slice(pos, pos + 7);
      if (matchStopPattern(stopWidths)) break;
    }

    if (pos + 6 > barWidths.length) break;
    const symbolWidths = barWidths.slice(pos, pos + 6);
    const val = matchPattern(symbolWidths);
    if (val === -1) return null; // unrecognized pattern
    values.push(val);
    pos += 6;
  }

  if (values.length < 3) return null; // need at least start + 1 data + checksum

  // Last value before stop is checksum
  const checksum = values[values.length - 1];
  const dataValues = values.slice(1, values.length - 1);

  // Verify checksum
  let sum = values[0]; // start code value
  for (let i = 0; i < dataValues.length; i++) {
    sum += dataValues[i] * (i + 1);
  }
  if (sum % 103 !== checksum) return null;

  // Convert Code128B values to characters
  let text = "";
  for (const v of dataValues) {
    text += String.fromCharCode(v + 32);
  }

  return text || null;
}

/**
 * Attempt to decode a Code128 barcode from a canvas element.
 * Scans multiple horizontal lines for robustness.
 * Returns decoded text or null.
 */
export function decodeAppGeneratedCode128FromCanvas(canvas: HTMLCanvasElement): string | null {
  const ctx = canvas.getContext("2d");
  if (!ctx) return null;

  const { width, height } = canvas;

  // Scan multiple horizontal lines across the barcode area
  const scanLines = [
    Math.floor(height * 0.25),
    Math.floor(height * 0.33),
    Math.floor(height * 0.40),
    Math.floor(height * 0.50),
    Math.floor(height * 0.60),
    Math.floor(height * 0.20),
    Math.floor(height * 0.70),
  ];

  for (const threshold of [128, 100, 160]) {
    for (const y of scanLines) {
      if (y < 0 || y >= height) continue;
      const result = decodeScanline(ctx, y, width, threshold);
      if (result && result.length >= 2) return result;
    }
  }

  return null;
}
